27-May-2025 00:01:52.375 SEVERE [http-nio-8080-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [uts.isd.controller.OrderServlet]
	jakarta.servlet.ServletException: Database connection not found in ServletContext.
		at uts.isd.controller.OrderServlet.init(OrderServlet.java:27)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1583)
27-May-2025 00:03:23.720 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [uts.isd.controller.OrderServlet]
	jakarta.servlet.ServletException: Database connection not found in ServletContext.
		at uts.isd.controller.OrderServlet.init(OrderServlet.java:27)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1583)
27-May-2025 00:03:28.370 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [uts.isd.controller.OrderServlet]
	jakarta.servlet.ServletException: Database connection not found in ServletContext.
		at uts.isd.controller.OrderServlet.init(OrderServlet.java:27)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1583)
27-May-2025 00:05:26.952 SEVERE [http-nio-8080-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [uts.isd.controller.OrderServlet]
	jakarta.servlet.ServletException: Database connection not found in ServletContext.
		at uts.isd.controller.OrderServlet.init(OrderServlet.java:27)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1583)
27-May-2025 00:05:28.901 SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [uts.isd.controller.OrderServlet]
	jakarta.servlet.ServletException: Database connection not found in ServletContext.
		at uts.isd.controller.OrderServlet.init(OrderServlet.java:27)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1583)
27-May-2025 00:05:49.446 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [uts.isd.controller.OrderServlet]
	jakarta.servlet.ServletException: Database connection not found in ServletContext.
		at uts.isd.controller.OrderServlet.init(OrderServlet.java:27)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1583)
27-May-2025 00:05:55.996 SEVERE [http-nio-8080-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [uts.isd.controller.OrderServlet]
	jakarta.servlet.ServletException: Database connection not found in ServletContext.
		at uts.isd.controller.OrderServlet.init(OrderServlet.java:27)
		at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
		at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:575)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:115)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
		at java.base/java.lang.Thread.run(Thread.java:1583)
